-- =============================================================================
-- HMS COMPLETE PRODUCTION SCHEMA MIGRATION (PUBLIC SCHEMA VERSION)
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Profiles Table (1:1 with auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'STUDENT' CHECK (role IN ('ADMIN', 'WARDEN', 'SECURITY', 'STUDENT')),
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    phone TEXT,
    avatar_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    legacy_django_id INTEGER UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

-- Role Helper Functions (Defined in public schema to avoid auth schema permission limits)
CREATE OR REPLACE FUNCTION public.user_role() 
RETURNS TEXT AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.is_admin() 
RETURNS BOOLEAN AS $$
  SELECT public.user_role() = 'ADMIN';
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.is_warden() 
RETURNS BOOLEAN AS $$
  SELECT public.user_role() = 'WARDEN';
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.is_security() 
RETURNS BOOLEAN AS $$
  SELECT public.user_role() = 'SECURITY';
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.is_student() 
RETURNS BOOLEAN AS $$
  SELECT public.user_role() = 'STUDENT';
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;

-- 2. Hostels Table
CREATE TABLE IF NOT EXISTS public.hostels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    gender CHAR(1) NOT NULL DEFAULT 'M' CHECK (gender IN ('M', 'F', 'C')),
    floor_count INTEGER NOT NULL DEFAULT 1 CHECK (floor_count >= 1),
    address TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Warden-Hostel M:N Assignments
CREATE TABLE IF NOT EXISTS public.warden_hostel_assignments (
    warden_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (warden_profile_id, hostel_id)
);
CREATE INDEX IF NOT EXISTS idx_warden_assignments_hostel ON public.warden_hostel_assignments(hostel_id);

CREATE OR REPLACE FUNCTION public.get_warden_hostel_ids(p_warden_id UUID)
RETURNS TABLE (hostel_id BIGINT) AS $$
  SELECT hostel_id 
  FROM public.warden_hostel_assignments
  WHERE warden_profile_id = p_warden_id;
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;

-- 3. Academic Courses
CREATE TABLE IF NOT EXISTS public.hostel_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT,
    room_type CHAR(1) NOT NULL DEFAULT 'D' CHECK (room_type IN ('S', 'D', 'P', 'B')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Rooms and Physical Beds
CREATE TABLE IF NOT EXISTS public.hostel_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    no TEXT NOT NULL,
    floor INTEGER NOT NULL DEFAULT 0,
    capacity INTEGER NOT NULL DEFAULT 2 CHECK (capacity >= 1),
    room_type CHAR(1) NOT NULL DEFAULT 'D' CHECK (room_type IN ('S', 'D', 'T', 'P', 'B')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_room_no_per_hostel UNIQUE (hostel_id, no)
);
CREATE INDEX IF NOT EXISTS idx_rooms_hostel_floor ON public.hostel_rooms(hostel_id, floor);

CREATE TABLE IF NOT EXISTS public.beds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    bed_number INTEGER NOT NULL CHECK (bed_number >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bed_number_per_room UNIQUE (room_id, bed_number)
);
CREATE INDEX IF NOT EXISTS idx_beds_room ON public.beds(room_id);

-- 5. Unified Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID UNIQUE REFERENCES public.profiles(id) ON DELETE SET NULL,
    student_name TEXT NOT NULL,
    enrollment_no TEXT NOT NULL UNIQUE,
    father_name TEXT,
    course_id BIGINT REFERENCES public.hostel_courses(id) ON DELETE SET NULL,
    dob DATE,
    gender CHAR(1) NOT NULL DEFAULT 'M' CHECK (gender IN ('M', 'F')),
    phone TEXT,
    guardian_phone TEXT,
    emergency_contact TEXT,
    no_dues BOOLEAN NOT NULL DEFAULT TRUE,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ALUMNI', 'SUSPENDED', 'WITHDRAWN')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_students_enrollment ON public.students(enrollment_no);
CREATE INDEX IF NOT EXISTS idx_students_profile ON public.students(profile_id);

-- 6. Room Allocations
CREATE TABLE IF NOT EXISTS public.room_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    bed_id BIGINT NOT NULL REFERENCES public.beds(id) ON DELETE RESTRICT,
    allocated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    allocated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    vacated_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_allocation_active_vacated CHECK (
        (is_active = TRUE AND vacated_at IS NULL) OR 
        (is_active = FALSE AND vacated_at IS NOT NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_single_active_student_alloc ON public.room_allocations (student_id) WHERE is_active = TRUE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_single_active_bed_alloc ON public.room_allocations (bed_id) WHERE is_active = TRUE;

-- 7. Issues & Audit Updates
CREATE TABLE IF NOT EXISTS public.issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    category TEXT NOT NULL CHECK (category IN ('PLUMBING', 'ELECTRICAL', 'CARPENTRY', 'WIFI', 'CLEANLINESS', 'OTHER')),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'waiting_for_workers', 'completed')),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_issues_hostel_status ON public.issues(hostel_id, status);

CREATE TABLE IF NOT EXISTS public.issue_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES public.issues(id) ON DELETE RESTRICT,
    old_status TEXT,
    new_status TEXT NOT NULL,
    note TEXT,
    updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Gate Passes
CREATE TABLE IF NOT EXISTS public.gate_passes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    pass_type TEXT NOT NULL DEFAULT 'DAY_OUT' CHECK (pass_type IN ('DAY_OUT', 'NIGHT_OUT', 'HOME_VISIT', 'EMERGENCY')),
    reason TEXT NOT NULL,
    out_date DATE NOT NULL,
    out_time TIME NOT NULL,
    expected_return_date DATE NOT NULL,
    expected_return_time TIME NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'expired', 'completed')),
    approved_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action_note TEXT,
    actioned_at TIMESTAMPTZ,
    actual_exit_time TIMESTAMPTZ,
    actual_entry_time TIMESTAMPTZ,
    is_late BOOLEAN NOT NULL DEFAULT FALSE,
    security_guard_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_gate_passes_token ON public.gate_passes(token);

-- 9. Visitor Logs
CREATE TABLE IF NOT EXISTS public.visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    visitor_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    purpose TEXT NOT NULL,
    check_in_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    check_out_time TIMESTAMPTZ,
    recorded_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Dining & Meal Skips
CREATE TABLE IF NOT EXISTS public.meal_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name IN ('BR', 'LN', 'SN', 'DN')),
    description TEXT,
    time_from TIME,
    time_to TIME,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    vegetarian BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    day_of_week CHAR(1) NOT NULL CHECK (day_of_week BETWEEN '0' AND '6'),
    meal_type_id BIGINT NOT NULL REFERENCES public.meal_types(id) ON DELETE RESTRICT,
    is_recurring BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_menu_hostel_day_meal UNIQUE (hostel_id, day_of_week, meal_type_id)
);

CREATE TABLE IF NOT EXISTS public.menu_item_links (
    menu_id BIGINT NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
    PRIMARY KEY (menu_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.student_meal_skips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    date DATE NOT NULL,
    meal_type_id BIGINT NOT NULL REFERENCES public.meal_types(id) ON DELETE RESTRICT,
    skip_type TEXT NOT NULL DEFAULT 'SKIP' CHECK (skip_type IN ('SKIP', 'LEAVE', 'RETURN')),
    reason TEXT,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_student_meal_skip UNIQUE (student_id, date, meal_type_id)
);

-- 11. Stored Procedures (RPCs)
CREATE OR REPLACE FUNCTION public.create_room_with_beds(
  p_hostel_id BIGINT,
  p_room_no TEXT,
  p_floor INTEGER,
  p_capacity INTEGER,
  p_room_type CHAR(1) DEFAULT 'D'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_new_room_id BIGINT;
  i INTEGER;
BEGIN
  IF public.user_role() != 'ADMIN' THEN
    RAISE EXCEPTION 'Access Denied: Only Admins can create rooms';
  END IF;
  IF p_capacity < 1 THEN
    RAISE EXCEPTION 'Capacity must be at least 1';
  END IF;

  INSERT INTO public.hostel_rooms (hostel_id, no, floor, capacity, room_type)
  VALUES (p_hostel_id, p_room_no, p_floor, p_capacity, p_room_type)
  RETURNING id INTO v_new_room_id;

  FOR i IN 1..p_capacity LOOP
    INSERT INTO public.beds (room_id, bed_number)
    VALUES (v_new_room_id, i);
  END LOOP;

  RETURN v_new_room_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.resize_room_capacity(
  p_room_id BIGINT,
  p_new_capacity INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_old_capacity INTEGER;
  v_occupied_beds_in_excess INTEGER;
  i INTEGER;
BEGIN
  IF public.user_role() != 'ADMIN' THEN
    RAISE EXCEPTION 'Access Denied: Only Admins can resize room capacity';
  END IF;
  IF p_new_capacity < 1 THEN
    RAISE EXCEPTION 'Capacity must be at least 1';
  END IF;

  SELECT capacity INTO v_old_capacity 
  FROM public.hostel_rooms 
  WHERE id = p_room_id FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Room % not found', p_room_id; END IF;
  IF p_new_capacity = v_old_capacity THEN
    RETURN jsonb_build_object('success', true, 'message', 'Capacity unchanged');
  END IF;

  IF p_new_capacity > v_old_capacity THEN
    UPDATE public.hostel_rooms SET capacity = p_new_capacity, updated_at = NOW() WHERE id = p_room_id;
    FOR i IN (v_old_capacity + 1)..p_new_capacity LOOP
      INSERT INTO public.beds (room_id, bed_number) VALUES (p_room_id, i);
    END LOOP;
  ELSE
    SELECT COUNT(*) INTO v_occupied_beds_in_excess
    FROM public.beds b
    JOIN public.room_allocations a ON a.bed_id = b.id AND a.is_active = TRUE
    WHERE b.room_id = p_room_id AND b.bed_number > p_new_capacity;

    IF v_occupied_beds_in_excess > 0 THEN
      RAISE EXCEPTION 'Cannot reduce capacity: % bed(s) in the reduction zone are currently occupied. Vacate or reassign residents first.', v_occupied_beds_in_excess;
    END IF;

    DELETE FROM public.beds
    WHERE room_id = p_room_id AND bed_number > p_new_capacity;

    UPDATE public.hostel_rooms SET capacity = p_new_capacity, updated_at = NOW() WHERE id = p_room_id;
  END IF;

  RETURN jsonb_build_object('success', true, 'room_id', p_room_id, 'old_capacity', v_old_capacity, 'new_capacity', p_new_capacity);
END;
$$;

CREATE OR REPLACE FUNCTION public.decommission_room(p_room_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF public.user_role() != 'ADMIN' THEN
    RAISE EXCEPTION 'Access Denied: Only Admins can decommission rooms';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.beds b
    JOIN public.room_allocations a ON a.bed_id = b.id AND a.is_active = TRUE
    WHERE b.room_id = p_room_id
  ) THEN
    RAISE EXCEPTION 'Cannot decommission room: Residents are currently allocated. Vacate all beds first.';
  END IF;

  UPDATE public.hostel_rooms SET is_active = FALSE, updated_at = NOW() WHERE id = p_room_id;
  RETURN jsonb_build_object('success', true, 'room_id', p_room_id, 'is_active', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.allocate_student_room(
  p_student_id BIGINT,
  p_bed_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
  v_room_id BIGINT;
  v_hostel_id BIGINT;
  v_student_status TEXT;
  v_existing_alloc_id BIGINT;
  v_new_alloc_id BIGINT;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'WARDEN') THEN
    RAISE EXCEPTION 'Access Denied: Only Admins and Wardens can allocate rooms';
  END IF;

  SELECT b.room_id, r.hostel_id INTO v_room_id, v_hostel_id
  FROM public.beds b
  JOIN public.hostel_rooms r ON b.room_id = r.id
  JOIN public.hostels h ON r.hostel_id = h.id
  WHERE b.id = p_bed_id AND r.is_active = TRUE AND h.is_active = TRUE
  FOR UPDATE OF b;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Bed % not found or belongs to an inactive room/hostel', p_bed_id;
  END IF;

  IF v_caller_role = 'WARDEN' AND NOT EXISTS (
    SELECT 1 FROM public.warden_hostel_assignments 
    WHERE warden_profile_id = auth.uid() AND hostel_id = v_hostel_id
  ) THEN
    RAISE EXCEPTION 'Access Denied: You cannot allocate residents to an unassigned hostel block';
  END IF;

  SELECT status INTO v_student_status
  FROM public.students
  WHERE id = p_student_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Student % not found', p_student_id; END IF;
  IF v_student_status != 'ACTIVE' THEN
    RAISE EXCEPTION 'Cannot allocate inactive resident (Status: %)', v_student_status;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.room_allocations 
    WHERE bed_id = p_bed_id AND is_active = TRUE
  ) THEN
    RAISE EXCEPTION 'Bed % is already occupied', p_bed_id;
  END IF;

  SELECT id INTO v_existing_alloc_id
  FROM public.room_allocations
  WHERE student_id = p_student_id AND is_active = TRUE
  FOR UPDATE;

  IF v_existing_alloc_id IS NOT NULL THEN
    UPDATE public.room_allocations
    SET is_active = FALSE, vacated_at = NOW(), updated_at = NOW()
    WHERE id = v_existing_alloc_id;
  END IF;

  INSERT INTO public.room_allocations (student_id, bed_id, allocated_by, is_active)
  VALUES (p_student_id, p_bed_id, auth.uid(), TRUE)
  RETURNING id INTO v_new_alloc_id;

  RETURN jsonb_build_object(
    'success', true,
    'allocation_id', v_new_alloc_id,
    'student_id', p_student_id,
    'bed_id', p_bed_id,
    'reallocated', v_existing_alloc_id IS NOT NULL
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.vacate_student_room(p_student_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
  v_alloc_id BIGINT;
  v_hostel_id BIGINT;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'WARDEN') THEN
    RAISE EXCEPTION 'Access Denied: Only Admins and Wardens can vacate rooms';
  END IF;

  SELECT a.id, r.hostel_id INTO v_alloc_id, v_hostel_id
  FROM public.room_allocations a
  JOIN public.beds b ON a.bed_id = b.id
  JOIN public.hostel_rooms r ON b.room_id = r.id
  WHERE a.student_id = p_student_id AND a.is_active = TRUE
  FOR UPDATE OF a;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active room allocation found for student %', p_student_id;
  END IF;

  IF v_caller_role = 'WARDEN' AND NOT EXISTS (
    SELECT 1 FROM public.warden_hostel_assignments 
    WHERE warden_profile_id = auth.uid() AND hostel_id = v_hostel_id
  ) THEN
    RAISE EXCEPTION 'Access Denied: You cannot vacate a resident from an unassigned hostel block';
  END IF;

  UPDATE public.room_allocations
  SET is_active = FALSE, vacated_at = NOW(), updated_at = NOW()
  WHERE id = v_alloc_id;

  RETURN jsonb_build_object('success', true, 'student_id', p_student_id, 'vacated_allocation_id', v_alloc_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.update_issue_status(
  p_issue_id BIGINT,
  p_new_status TEXT,
  p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
  v_old_status TEXT;
  v_hostel_id BIGINT;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'WARDEN') THEN
    RAISE EXCEPTION 'Access Denied: Only Admins and Wardens can update ticket status';
  END IF;

  SELECT status, hostel_id INTO v_old_status, v_hostel_id
  FROM public.issues
  WHERE id = p_issue_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Issue % not found', p_issue_id; END IF;

  IF v_caller_role = 'WARDEN' AND NOT EXISTS (
    SELECT 1 FROM public.warden_hostel_assignments 
    WHERE warden_profile_id = auth.uid() AND hostel_id = v_hostel_id
  ) THEN
    RAISE EXCEPTION 'Access Denied: Issue belongs to an unassigned hostel block';
  END IF;

  IF p_new_status NOT IN ('pending', 'in_progress', 'waiting_for_workers', 'completed') THEN
    RAISE EXCEPTION 'Invalid status: %', p_new_status;
  END IF;

  UPDATE public.issues
  SET status = p_new_status,
      resolved_at = CASE WHEN p_new_status = 'completed' THEN NOW() ELSE NULL END,
      updated_at = NOW()
  WHERE id = p_issue_id;

  INSERT INTO public.issue_updates (
    issue_id, old_status, new_status, note, updated_by, created_at
  ) VALUES (
    p_issue_id, v_old_status, p_new_status, p_note, auth.uid(), NOW()
  );

  RETURN jsonb_build_object('success', true, 'issue_id', p_issue_id, 'new_status', p_new_status);
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_gate_pass(
  p_pass_id BIGINT,
  p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
  v_hostel_id BIGINT;
  v_status TEXT;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'WARDEN') THEN
    RAISE EXCEPTION 'Access Denied: Only Admins and Wardens can approve gate passes';
  END IF;

  SELECT hostel_id, status INTO v_hostel_id, v_status
  FROM public.gate_passes WHERE id = p_pass_id FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Gate pass % not found', p_pass_id; END IF;
  IF v_status != 'pending' THEN RAISE EXCEPTION 'Only pending passes can be approved (Current: %)', v_status; END IF;

  IF v_caller_role = 'WARDEN' AND NOT EXISTS (
    SELECT 1 FROM public.warden_hostel_assignments 
    WHERE warden_profile_id = auth.uid() AND hostel_id = v_hostel_id
  ) THEN
    RAISE EXCEPTION 'Access Denied: You cannot approve passes for an unassigned hostel block';
  END IF;

  UPDATE public.gate_passes
  SET status = 'approved',
      approved_by = auth.uid(),
      action_note = p_note,
      actioned_at = NOW(),
      updated_at = NOW()
  WHERE id = p_pass_id;

  RETURN jsonb_build_object('success', true, 'pass_id', p_pass_id, 'status', 'approved');
END;
$$;

CREATE OR REPLACE FUNCTION public.reject_gate_pass(
  p_pass_id BIGINT,
  p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
  v_hostel_id BIGINT;
  v_status TEXT;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'WARDEN') THEN
    RAISE EXCEPTION 'Access Denied: Only Admins and Wardens can reject gate passes';
  END IF;

  SELECT hostel_id, status INTO v_hostel_id, v_status
  FROM public.gate_passes WHERE id = p_pass_id FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Gate pass % not found', p_pass_id; END IF;
  IF v_status != 'pending' THEN RAISE EXCEPTION 'Only pending passes can be rejected (Current: %)', v_status; END IF;

  IF v_caller_role = 'WARDEN' AND NOT EXISTS (
    SELECT 1 FROM public.warden_hostel_assignments 
    WHERE warden_profile_id = auth.uid() AND hostel_id = v_hostel_id
  ) THEN
    RAISE EXCEPTION 'Access Denied: You cannot reject passes for an unassigned hostel block';
  END IF;

  UPDATE public.gate_passes
  SET status = 'rejected',
      approved_by = auth.uid(),
      action_note = p_note,
      actioned_at = NOW(),
      updated_at = NOW()
  WHERE id = p_pass_id;

  RETURN jsonb_build_object('success', true, 'pass_id', p_pass_id, 'status', 'rejected');
END;
$$;

CREATE OR REPLACE FUNCTION public.log_gate_movement(
  p_pass_id BIGINT,
  p_movement_type TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
  v_pass RECORD;
  v_is_late BOOLEAN := FALSE;
  v_deadline TIMESTAMPTZ;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'SECURITY') THEN
    RAISE EXCEPTION 'Access Denied: Only Security Guards or Admins can log gate movements';
  END IF;

  SELECT * INTO v_pass FROM public.gate_passes WHERE id = p_pass_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Gate pass % not found', p_pass_id; END IF;

  IF v_pass.status != 'approved' THEN
    RAISE EXCEPTION 'Cannot log movement: Pass status is % (must be approved)', v_pass.status;
  END IF;

  v_deadline := (v_pass.expected_return_date + v_pass.expected_return_time);

  IF p_movement_type = 'EXIT' THEN
    IF v_pass.actual_exit_time IS NOT NULL THEN
      RAISE EXCEPTION 'Exit already stamped at %', v_pass.actual_exit_time;
    END IF;
    IF NOW() > v_deadline THEN
      UPDATE public.gate_passes SET status = 'expired', updated_at = NOW() WHERE id = p_pass_id;
      RAISE EXCEPTION 'Cannot log EXIT: Return deadline has passed. Pass is expired.';
    END IF;

    UPDATE public.gate_passes
    SET actual_exit_time = NOW(), security_guard_id = auth.uid(), updated_at = NOW()
    WHERE id = p_pass_id;

  ELSIF p_movement_type = 'ENTRY' THEN
    IF v_pass.actual_exit_time IS NULL THEN
      RAISE EXCEPTION 'Invalid movement sequence: Cannot stamp ENTRY before EXIT';
    END IF;
    IF v_pass.actual_entry_time IS NOT NULL THEN
      RAISE EXCEPTION 'Entry already stamped at %', v_pass.actual_entry_time;
    END IF;

    v_is_late := NOW() > v_deadline;

    UPDATE public.gate_passes
    SET actual_entry_time = NOW(),
        status = 'completed',
        is_late = v_is_late,
        security_guard_id = auth.uid(),
        updated_at = NOW()
    WHERE id = p_pass_id;
  ELSE
    RAISE EXCEPTION 'Invalid movement type: %', p_movement_type;
  END IF;

  RETURN jsonb_build_object('success', true, 'pass_id', p_pass_id, 'movement', p_movement_type, 'is_late', v_is_late);
END;
$$;

CREATE OR REPLACE FUNCTION public.checkout_visitor(p_visitor_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller_role TEXT;
BEGIN
  v_caller_role := public.user_role();
  IF v_caller_role NOT IN ('ADMIN', 'SECURITY') THEN
    RAISE EXCEPTION 'Access Denied: Only Security Guards or Admins can check out visitors';
  END IF;

  UPDATE public.visitor_logs
  SET check_out_time = NOW(), updated_at = NOW()
  WHERE id = p_visitor_id AND check_out_time IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Visitor log % not found or already checked out', p_visitor_id;
  END IF;

  RETURN jsonb_build_object('success', true, 'visitor_id', p_visitor_id, 'checked_out_at', NOW());
END;
$$;

CREATE OR REPLACE FUNCTION public.update_my_profile(
  p_phone TEXT,
  p_avatar_url TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE public.profiles
  SET phone = p_phone,
      avatar_url = p_avatar_url,
      updated_at = NOW()
  WHERE id = auth.uid();

  UPDATE public.students
  SET phone = p_phone, updated_at = NOW()
  WHERE profile_id = auth.uid();

  RETURN jsonb_build_object('success', true, 'profile_id', auth.uid());
END;
$$;

-- 12. Triggers for Immutable Location Snapshots
CREATE OR REPLACE FUNCTION public.trig_fn_snapshot_student_location()
RETURNS TRIGGER AS $$
DECLARE
  v_hostel_id BIGINT;
  v_room_id BIGINT;
BEGIN
  SELECT r.hostel_id, r.id INTO v_hostel_id, v_room_id
  FROM public.room_allocations a
  JOIN public.beds b ON a.bed_id = b.id
  JOIN public.hostel_rooms r ON b.room_id = r.id
  WHERE a.student_id = NEW.student_id AND a.is_active = TRUE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Cannot create record: Student % has no active room allocation.', NEW.student_id;
  END IF;

  NEW.hostel_id := v_hostel_id;
  IF TG_TABLE_NAME IN ('issues', 'gate_passes', 'visitor_logs') THEN
    NEW.room_id := v_room_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

DROP TRIGGER IF EXISTS tr_snapshot_issues_loc ON public.issues;
CREATE TRIGGER tr_snapshot_issues_loc BEFORE INSERT ON public.issues
FOR EACH ROW EXECUTE FUNCTION public.trig_fn_snapshot_student_location();

DROP TRIGGER IF EXISTS tr_snapshot_gate_loc ON public.gate_passes;
CREATE TRIGGER tr_snapshot_gate_loc BEFORE INSERT ON public.gate_passes
FOR EACH ROW EXECUTE FUNCTION public.trig_fn_snapshot_student_location();

DROP TRIGGER IF EXISTS tr_snapshot_visitor_loc ON public.visitor_logs;
CREATE TRIGGER tr_snapshot_visitor_loc BEFORE INSERT ON public.visitor_logs
FOR EACH ROW EXECUTE FUNCTION public.trig_fn_snapshot_student_location();

DROP TRIGGER IF EXISTS tr_snapshot_mealskip_loc ON public.student_meal_skips;
CREATE TRIGGER tr_snapshot_mealskip_loc BEFORE INSERT ON public.student_meal_skips
FOR EACH ROW EXECUTE FUNCTION public.trig_fn_snapshot_student_location();

-- 13. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hostels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warden_hostel_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hostel_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hostel_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issue_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gate_passes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_item_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_meal_skips ENABLE ROW LEVEL SECURITY;

-- 14. Policies
DROP POLICY IF EXISTS policy_profiles_select ON public.profiles;
CREATE POLICY policy_profiles_select ON public.profiles FOR SELECT TO authenticated
USING (public.is_admin() OR public.is_warden() OR public.is_security() OR id = auth.uid());

DROP POLICY IF EXISTS policy_profiles_update_admin ON public.profiles;
CREATE POLICY policy_profiles_update_admin ON public.profiles FOR UPDATE TO authenticated
USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS policy_hostels_select ON public.hostels;
CREATE POLICY policy_hostels_select ON public.hostels FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_hostels_admin ON public.hostels;
CREATE POLICY policy_hostels_admin ON public.hostels FOR ALL TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS policy_warden_assignments_select ON public.warden_hostel_assignments;
CREATE POLICY policy_warden_assignments_select ON public.warden_hostel_assignments FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_warden_assignments_admin ON public.warden_hostel_assignments;
CREATE POLICY policy_warden_assignments_admin ON public.warden_hostel_assignments FOR ALL TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS policy_rooms_select ON public.hostel_rooms;
CREATE POLICY policy_rooms_select ON public.hostel_rooms FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_beds_select ON public.beds;
CREATE POLICY policy_beds_select ON public.beds FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_courses_select ON public.hostel_courses;
CREATE POLICY policy_courses_select ON public.hostel_courses FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_courses_admin ON public.hostel_courses;
CREATE POLICY policy_courses_admin ON public.hostel_courses FOR ALL TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS policy_students_select ON public.students;
CREATE POLICY policy_students_select ON public.students FOR SELECT TO authenticated
USING (
  public.is_admin() 
  OR profile_id = auth.uid()
  OR public.is_security()
  OR (public.is_warden() AND EXISTS (
    SELECT 1 FROM public.room_allocations a
    JOIN public.beds b ON a.bed_id = b.id
    JOIN public.hostel_rooms r ON b.room_id = r.id
    WHERE a.student_id = public.students.id 
      AND a.is_active = TRUE 
      AND r.hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid()))
  ))
);
DROP POLICY IF EXISTS policy_students_admin ON public.students;
CREATE POLICY policy_students_admin ON public.students FOR ALL TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS policy_allocations_select ON public.room_allocations;
CREATE POLICY policy_allocations_select ON public.room_allocations FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR public.is_security()
  OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR (public.is_warden() AND EXISTS (
    SELECT 1 FROM public.beds b
    JOIN public.hostel_rooms r ON b.room_id = r.id
    WHERE b.id = bed_id AND r.hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid()))
  ))
);

DROP POLICY IF EXISTS policy_issues_select ON public.issues;
CREATE POLICY policy_issues_select ON public.issues FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR public.is_security()
  OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR (public.is_warden() AND hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid())))
);

DROP POLICY IF EXISTS policy_issues_insert_student ON public.issues;
CREATE POLICY policy_issues_insert_student ON public.issues FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR public.is_admin()
);

DROP POLICY IF EXISTS policy_issue_updates_select ON public.issue_updates;
CREATE POLICY policy_issue_updates_select ON public.issue_updates FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR (public.is_warden() AND EXISTS (
    SELECT 1 FROM public.issues i WHERE i.id = issue_id AND i.hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid()))
  ))
  OR EXISTS (
    SELECT 1 FROM public.issues i 
    JOIN public.students s ON i.student_id = s.id 
    WHERE i.id = issue_id AND s.profile_id = auth.uid()
  )
);

DROP POLICY IF EXISTS policy_gate_passes_select ON public.gate_passes;
CREATE POLICY policy_gate_passes_select ON public.gate_passes FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR public.is_security()
  OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR (public.is_warden() AND hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid())))
);

DROP POLICY IF EXISTS policy_gate_passes_insert ON public.gate_passes;
CREATE POLICY policy_gate_passes_insert ON public.gate_passes FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR public.is_admin()
);

DROP POLICY IF EXISTS policy_visitor_logs_select ON public.visitor_logs;
CREATE POLICY policy_visitor_logs_select ON public.visitor_logs FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR public.is_security()
  OR (public.is_warden() AND hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid())))
  OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
);

DROP POLICY IF EXISTS policy_visitor_logs_insert ON public.visitor_logs;
CREATE POLICY policy_visitor_logs_insert ON public.visitor_logs FOR INSERT TO authenticated
WITH CHECK (public.is_admin() OR public.is_security());

DROP POLICY IF EXISTS policy_meal_types_select ON public.meal_types;
CREATE POLICY policy_meal_types_select ON public.meal_types FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_meal_types_admin ON public.meal_types;
CREATE POLICY policy_meal_types_admin ON public.meal_types FOR ALL TO authenticated USING (public.is_admin() OR public.is_warden()) WITH CHECK (public.is_admin() OR public.is_warden());

DROP POLICY IF EXISTS policy_menu_items_select ON public.menu_items;
CREATE POLICY policy_menu_items_select ON public.menu_items FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_menu_items_admin ON public.menu_items;
CREATE POLICY policy_menu_items_admin ON public.menu_items FOR ALL TO authenticated USING (public.is_admin() OR public.is_warden()) WITH CHECK (public.is_admin() OR public.is_warden());

DROP POLICY IF EXISTS policy_menus_select ON public.menus;
CREATE POLICY policy_menus_select ON public.menus FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_menus_admin ON public.menus;
CREATE POLICY policy_menus_admin ON public.menus FOR ALL TO authenticated USING (public.is_admin() OR public.is_warden()) WITH CHECK (public.is_admin() OR public.is_warden());

DROP POLICY IF EXISTS policy_menu_item_links_select ON public.menu_item_links;
CREATE POLICY policy_menu_item_links_select ON public.menu_item_links FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS policy_menu_item_links_admin ON public.menu_item_links;
CREATE POLICY policy_menu_item_links_admin ON public.menu_item_links FOR ALL TO authenticated USING (public.is_admin() OR public.is_warden()) WITH CHECK (public.is_admin() OR public.is_warden());

DROP POLICY IF EXISTS policy_meal_skips_select ON public.student_meal_skips;
CREATE POLICY policy_meal_skips_select ON public.student_meal_skips FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR (public.is_warden() AND hostel_id IN (SELECT public.get_warden_hostel_ids(auth.uid())))
  OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
);

DROP POLICY IF EXISTS policy_meal_skips_insert ON public.student_meal_skips;
CREATE POLICY policy_meal_skips_insert ON public.student_meal_skips FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR public.is_admin()
);

DROP POLICY IF EXISTS policy_meal_skips_delete ON public.student_meal_skips;
CREATE POLICY policy_meal_skips_delete ON public.student_meal_skips FOR DELETE TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.profile_id = auth.uid())
  OR public.is_admin()
);

-- 15. Storage Bucket & Policies
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS avatar_select ON storage.objects;
CREATE POLICY avatar_select ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS avatar_insert ON storage.objects;
CREATE POLICY avatar_insert ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS avatar_update ON storage.objects;
CREATE POLICY avatar_update ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS avatar_delete ON storage.objects;
CREATE POLICY avatar_delete ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'avatars' AND ((storage.foldername(name))[1] = auth.uid()::text OR public.is_admin()));

-- 16. Views
CREATE OR REPLACE VIEW public.view_admin_dashboard_stats AS
SELECT 
  (SELECT COUNT(*) FROM public.hostels WHERE is_active = TRUE) AS total_hostels,
  (SELECT COUNT(*) FROM public.hostel_rooms WHERE is_active = TRUE) AS total_rooms,
  (SELECT COUNT(*) FROM public.beds b JOIN public.hostel_rooms r ON b.room_id = r.id WHERE r.is_active = TRUE) AS total_capacity,
  (SELECT COUNT(*) FROM public.room_allocations WHERE is_active = TRUE) AS occupied_beds,
  (SELECT COUNT(*) FROM public.beds b JOIN public.hostel_rooms r ON b.room_id = r.id WHERE r.is_active = TRUE) - 
  (SELECT COUNT(*) FROM public.room_allocations WHERE is_active = TRUE) AS vacant_beds,
  CASE WHEN (SELECT COUNT(*) FROM public.beds b JOIN public.hostel_rooms r ON b.room_id = r.id WHERE r.is_active = TRUE) > 0 
       THEN ROUND(((SELECT COUNT(*) FROM public.room_allocations WHERE is_active = TRUE)::NUMERIC / 
            (SELECT COUNT(*) FROM public.beds b JOIN public.hostel_rooms r ON b.room_id = r.id WHERE r.is_active = TRUE)::NUMERIC * 100), 1)
       ELSE 0 END AS occupancy_rate,
  (SELECT COUNT(*) FROM public.gate_passes WHERE status = 'pending') AS pending_gate_passes,
  (SELECT COUNT(*) FROM public.issues WHERE status != 'completed') AS active_issues;

CREATE OR REPLACE VIEW public.view_warden_dashboard_stats 
WITH (security_invoker = true) AS
SELECT 
  h.id AS hostel_id,
  h.name AS hostel_name,
  h.gender,
  h.floor_count,
  COUNT(DISTINCT hr.id) AS total_rooms,
  COUNT(DISTINCT b.id) AS total_capacity,
  COUNT(DISTINCT a.id) FILTER (WHERE a.is_active = TRUE) AS occupied_beds,
  COUNT(DISTINCT b.id) - COUNT(DISTINCT a.id) FILTER (WHERE a.is_active = TRUE) AS vacant_beds,
  (SELECT COUNT(*) FROM public.gate_passes gp WHERE gp.hostel_id = h.id AND gp.status = 'pending') AS pending_gate_passes,
  (SELECT COUNT(*) FROM public.issues iss WHERE iss.hostel_id = h.id AND iss.status != 'completed') AS open_issues
FROM public.hostels h
JOIN public.warden_hostel_assignments wha ON wha.hostel_id = h.id AND wha.warden_profile_id = auth.uid()
LEFT JOIN public.hostel_rooms hr ON hr.hostel_id = h.id AND hr.is_active = TRUE
LEFT JOIN public.beds b ON b.room_id = hr.id
LEFT JOIN public.room_allocations a ON a.bed_id = b.id AND a.is_active = TRUE
GROUP BY h.id, h.name, h.gender, h.floor_count;

-- 17. Revoke Direct Mutations & Grant Execution
REVOKE INSERT, UPDATE, DELETE ON public.hostel_rooms FROM PUBLIC, anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.beds FROM PUBLIC, anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.room_allocations FROM PUBLIC, anon, authenticated;
REVOKE UPDATE, DELETE ON public.issue_updates FROM PUBLIC, anon, authenticated;
REVOKE INSERT ON public.issue_updates FROM PUBLIC, anon, authenticated;
REVOKE UPDATE ON public.issues FROM PUBLIC, anon, authenticated;
REVOKE UPDATE ON public.gate_passes FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.create_room_with_beds FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.resize_room_capacity FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.decommission_room FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.allocate_student_room FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.vacate_student_room FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_issue_status FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.approve_gate_pass FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reject_gate_pass FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_gate_movement FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.checkout_visitor FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_my_profile FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.create_room_with_beds TO authenticated;
GRANT EXECUTE ON FUNCTION public.resize_room_capacity TO authenticated;
GRANT EXECUTE ON FUNCTION public.decommission_room TO authenticated;
GRANT EXECUTE ON FUNCTION public.allocate_student_room TO authenticated;
GRANT EXECUTE ON FUNCTION public.vacate_student_room TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_issue_status TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_gate_pass TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_gate_pass TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_gate_movement TO authenticated;
GRANT EXECUTE ON FUNCTION public.checkout_visitor TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_my_profile TO authenticated;
