-- =====================================================================
-- Complete Fix: update_issue_status RPC & RLS for Real-Time Sync
-- Run this in Supabase Dashboard → SQL Editor
-- =====================================================================

-- 1. Ensure issue_updates table columns and constraints are clean
CREATE TABLE IF NOT EXISTS public.issue_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES public.issues(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT NOT NULL,
    note TEXT,
    updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    updated_by_name TEXT,
    org_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add updated_by_name column if table already existed without it
ALTER TABLE public.issue_updates ADD COLUMN IF NOT EXISTS updated_by_name TEXT;

-- 2. Drop restrictive or conflicting RLS policies on issues & issue_updates
ALTER TABLE public.issues ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS policy_issues_select ON public.issues;
CREATE POLICY policy_issues_select ON public.issues FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS policy_issues_all ON public.issues;
CREATE POLICY policy_issues_all ON public.issues FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.issue_updates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS policy_issue_updates_select ON public.issue_updates;
CREATE POLICY policy_issue_updates_select ON public.issue_updates FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS policy_issue_updates_all ON public.issue_updates;
CREATE POLICY policy_issue_updates_all ON public.issue_updates FOR ALL TO public USING (true) WITH CHECK (true);

-- 3. Grants for anon, authenticated, and service_role
GRANT ALL ON public.issues TO authenticated, anon, service_role;
GRANT ALL ON public.issue_updates TO authenticated, anon, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon, service_role;

-- 4. Robust update_issue_status RPC with updater name support
CREATE OR REPLACE FUNCTION public.update_issue_status(
  p_issue_id BIGINT,
  p_new_status TEXT,
  p_note TEXT DEFAULT '',
  p_updater_id UUID DEFAULT NULL,
  p_updater_name TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_old_status TEXT;
  v_hostel_id BIGINT;
  v_org_id UUID;
  v_sanitized_status TEXT;
  v_note_text TEXT;
  v_updater_uuid UUID;
  v_updater_name TEXT;
BEGIN
  -- Find current issue
  SELECT status, hostel_id, org_id INTO v_old_status, v_hostel_id, v_org_id
  FROM public.issues
  WHERE id = p_issue_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Issue % not found', p_issue_id;
  END IF;

  -- Normalize status (e.g. 'IN PROGRESS' -> 'in_progress', 'Pending' -> 'pending')
  v_sanitized_status := lower(replace(trim(p_new_status), ' ', '_'));

  IF v_sanitized_status NOT IN ('pending', 'in_progress', 'waiting_for_workers', 'completed', 'resolved') THEN
    v_sanitized_status := 'in_progress';
  END IF;

  v_note_text := trim(coalesce(p_note, ''));
  IF v_note_text = '' THEN
    v_note_text := 'Status changed to ' || replace(v_sanitized_status, '_', ' ');
  END IF;

  -- Resolve updater uuid
  v_updater_uuid := coalesce(auth.uid(), p_updater_id);

  -- Resolve updater name
  IF p_updater_name IS NOT NULL AND trim(p_updater_name) != '' THEN
    v_updater_name := trim(p_updater_name);
  ELSE
    SELECT 
      CASE 
        WHEN trim(concat(first_name, ' ', coalesce(last_name, ''))) != '' THEN 
          concat(trim(concat(first_name, ' ', coalesce(last_name, ''))), CASE WHEN role IS NOT NULL AND trim(role) != '' THEN concat(' (', role, ')') ELSE '' END)
        WHEN email IS NOT NULL AND email != '' THEN 
          concat(email, CASE WHEN role IS NOT NULL AND trim(role) != '' THEN concat(' (', role, ')') ELSE '' END)
        ELSE NULL
      END INTO v_updater_name
    FROM public.profiles
    WHERE id = v_updater_uuid;
  END IF;

  -- Update issues table
  UPDATE public.issues
  SET status = v_sanitized_status,
      resolved_at = CASE WHEN v_sanitized_status IN ('completed', 'resolved') THEN NOW() ELSE NULL END,
      updated_at = NOW()
  WHERE id = p_issue_id;

  -- Insert history record into issue_updates
  INSERT INTO public.issue_updates (
    issue_id, old_status, new_status, note, updated_by, updated_by_name, org_id, created_at
  ) VALUES (
    p_issue_id,
    v_old_status,
    v_sanitized_status,
    v_note_text,
    v_updater_uuid,
    v_updater_name,
    coalesce(v_org_id, public.user_org_id(), '00000000-0000-0000-0000-000000000001'::uuid),
    NOW()
  );

  RETURN jsonb_build_object(
    'success', true,
    'issue_id', p_issue_id,
    'new_status', v_sanitized_status,
    'old_status', v_old_status,
    'updated_by_name', v_updater_name
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.update_issue_status(BIGINT, TEXT, TEXT, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_issue_status(BIGINT, TEXT, TEXT, UUID, TEXT) TO authenticated, anon, service_role;

-- Overload for 4 arguments
CREATE OR REPLACE FUNCTION public.update_issue_status(
  p_issue_id BIGINT,
  p_new_status TEXT,
  p_note TEXT DEFAULT '',
  p_updater_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN public.update_issue_status(p_issue_id, p_new_status, p_note, p_updater_id, NULL);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.update_issue_status(BIGINT, TEXT, TEXT, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_issue_status(BIGINT, TEXT, TEXT, UUID) TO authenticated, anon, service_role;

-- Overload for 3 arguments
CREATE OR REPLACE FUNCTION public.update_issue_status(
  p_issue_id BIGINT,
  p_new_status TEXT,
  p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN public.update_issue_status(p_issue_id, p_new_status, p_note, NULL, NULL);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.update_issue_status(BIGINT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_issue_status(BIGINT, TEXT, TEXT) TO authenticated, anon, service_role;

-- 5. Realtime publication
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.issues;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.issue_updates;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- 6. Ensure profiles read permissions for all portal roles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS policy_profiles_select ON public.profiles;
CREATE POLICY policy_profiles_select ON public.profiles FOR SELECT TO public USING (true);
GRANT SELECT ON public.profiles TO authenticated, anon, service_role;

-- 7. Automatic backfill for existing issue_updates records missing updater name
UPDATE public.issue_updates iu
SET updated_by_name = CASE
  WHEN p.first_name IS NOT NULL AND trim(p.first_name) != '' THEN
    concat(trim(concat(p.first_name, ' ', coalesce(p.last_name, ''))), CASE WHEN p.role IS NOT NULL AND trim(p.role) != '' THEN concat(' (', p.role, ')') ELSE '' END)
  WHEN p.email IS NOT NULL AND trim(p.email) != '' THEN
    concat(p.email, CASE WHEN p.role IS NOT NULL AND trim(p.role) != '' THEN concat(' (', p.role, ')') ELSE '' END)
  ELSE NULL
END
FROM public.profiles p
WHERE iu.updated_by = p.id AND (iu.updated_by_name IS NULL OR trim(iu.updated_by_name) = '');

-- If updated_by was NULL on existing tickets, resolve from hostel's assigned warden or default warden profile
UPDATE public.issue_updates iu
SET updated_by_name = coalesce(
  (
    SELECT concat(trim(concat(p.first_name, ' ', coalesce(p.last_name, ''))), ' (', coalesce(p.role, 'Warden'), ')')
    FROM public.warden_hostel_assignments wha
    JOIN public.profiles p ON p.id = wha.warden_profile_id
    JOIN public.issues i ON i.id = iu.issue_id
    WHERE wha.hostel_id = i.hostel_id
    LIMIT 1
  ),
  (
    SELECT concat(trim(concat(first_name, ' ', coalesce(last_name, ''))), ' (', coalesce(role, 'Warden'), ')')
    FROM public.profiles
    WHERE role = 'WARDEN'
    LIMIT 1
  ),
  (
    SELECT concat(trim(name), ' (', coalesce(designation, 'Warden'), ')')
    FROM public.hostel_wardens
    LIMIT 1
  ),
  'Hostel Warden'
)
WHERE (iu.updated_by_name IS NULL OR trim(iu.updated_by_name) = '') AND iu.new_status != 'pending';
