-- =============================================================================
-- Migration 003: Academic Courses
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.hostel_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT,
    room_type CHAR(1) NOT NULL DEFAULT 'D' CHECK (room_type IN ('S', 'D', 'P', 'B')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
