-- =============================================================================
-- Migration 004: Hostels and Multi-Warden Assignments
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.hostels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    gender CHAR(1) NOT NULL DEFAULT 'M' CHECK (gender IN ('M', 'F', 'C')),
    floor_count INTEGER NOT NULL DEFAULT 1 CHECK (floor_count >= 1),
    address TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- M:N Warden Assignments (Zero global fallback)
CREATE TABLE IF NOT EXISTS public.warden_hostel_assignments (
    warden_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (warden_profile_id, hostel_id)
);

CREATE INDEX IF NOT EXISTS idx_warden_assignments_hostel ON public.warden_hostel_assignments(hostel_id);

-- Helper to retrieve strictly assigned hostel IDs for a warden
CREATE OR REPLACE FUNCTION auth.get_warden_hostel_ids(p_warden_id UUID)
RETURNS TABLE (hostel_id BIGINT) AS $$
  SELECT hostel_id 
  FROM public.warden_hostel_assignments
  WHERE warden_profile_id = p_warden_id;
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp;
