-- =============================================================================
-- Migration 005: Rooms and Physical Beds
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.hostel_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    no TEXT NOT NULL,
    floor INTEGER NOT NULL DEFAULT 0,
    capacity INTEGER NOT NULL DEFAULT 2 CHECK (capacity >= 1),
    room_type CHAR(1) NOT NULL DEFAULT 'D' CHECK (room_type IN ('S', 'D', 'T', 'P', 'B')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_room_no_per_hostel UNIQUE (hostel_id, no)
);

CREATE INDEX IF NOT EXISTS idx_rooms_hostel_floor ON public.hostel_rooms(hostel_id, floor);

-- Physical Beds: Numeric bed numbers (Integer >= 1)
CREATE TABLE IF NOT EXISTS public.beds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    bed_number INTEGER NOT NULL CHECK (bed_number >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bed_number_per_room UNIQUE (room_id, bed_number)
);

CREATE INDEX IF NOT EXISTS idx_beds_room ON public.beds(room_id);
