-- =============================================================================
-- Migration 006: Unified Students Table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID UNIQUE REFERENCES public.profiles(id) ON DELETE SET NULL,
    student_name TEXT NOT NULL,
    enrollment_no TEXT NOT NULL UNIQUE,
    father_name TEXT,
    course_id BIGINT REFERENCES public.hostel_courses(id) ON DELETE SET NULL,
    dob DATE,
    gender CHAR(1) NOT NULL DEFAULT 'M' CHECK (gender IN ('M', 'F')),
    phone TEXT,
    guardian_phone TEXT,
    emergency_contact TEXT,
    no_dues BOOLEAN NOT NULL DEFAULT TRUE,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ALUMNI', 'SUSPENDED', 'WITHDRAWN')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_students_enrollment ON public.students(enrollment_no);
CREATE INDEX IF NOT EXISTS idx_students_profile ON public.students(profile_id);
