-- =============================================================================
-- Migration 007: Relational Room Allocations
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.room_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    bed_id BIGINT NOT NULL REFERENCES public.beds(id) ON DELETE RESTRICT,
    allocated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    allocated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    vacated_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_allocation_active_vacated CHECK (
        (is_active = TRUE AND vacated_at IS NULL) OR 
        (is_active = FALSE AND vacated_at IS NOT NULL)
    )
);

-- Partial Unique Invariants
CREATE UNIQUE INDEX IF NOT EXISTS uq_single_active_student_alloc 
ON public.room_allocations (student_id) 
WHERE is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_single_active_bed_alloc 
ON public.room_allocations (bed_id) 
WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_allocations_student ON public.room_allocations(student_id);
CREATE INDEX IF NOT EXISTS idx_allocations_bed ON public.room_allocations(bed_id);
