-- =============================================================================
-- Migration 008: Maintenance Issues & Updates
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    category TEXT NOT NULL CHECK (category IN ('PLUMBING', 'ELECTRICAL', 'CARPENTRY', 'WIFI', 'CLEANLINESS', 'OTHER')),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'waiting_for_workers', 'completed')),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_issues_hostel_status ON public.issues(hostel_id, status);
CREATE INDEX IF NOT EXISTS idx_issues_student ON public.issues(student_id);

CREATE TABLE IF NOT EXISTS public.issue_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES public.issues(id) ON DELETE RESTRICT,
    old_status TEXT,
    new_status TEXT NOT NULL,
    note TEXT,
    updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_issue_updates_issue ON public.issue_updates(issue_id, created_at);
