-- =============================================================================
-- Migration 009: Gate Passes with Historical Location Snapshots
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.gate_passes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    pass_type TEXT NOT NULL DEFAULT 'DAY_OUT' CHECK (pass_type IN ('DAY_OUT', 'NIGHT_OUT', 'HOME_VISIT', 'EMERGENCY')),
    reason TEXT NOT NULL,
    out_date DATE NOT NULL,
    out_time TIME NOT NULL,
    expected_return_date DATE NOT NULL,
    expected_return_time TIME NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'expired', 'completed')),
    approved_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action_note TEXT,
    actioned_at TIMESTAMPTZ,
    actual_exit_time TIMESTAMPTZ,
    actual_entry_time TIMESTAMPTZ,
    is_late BOOLEAN NOT NULL DEFAULT FALSE,
    security_guard_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gate_passes_token ON public.gate_passes(token);
CREATE INDEX IF NOT EXISTS idx_gate_passes_hostel_status ON public.gate_passes(hostel_id, status);
CREATE INDEX IF NOT EXISTS idx_gate_passes_student ON public.gate_passes(student_id);
