-- =============================================================================
-- Migration 010: Visitor Logs with Historical Room Snapshot
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    room_id BIGINT NOT NULL REFERENCES public.hostel_rooms(id) ON DELETE RESTRICT,
    visitor_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    purpose TEXT NOT NULL,
    check_in_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    check_out_time TIMESTAMPTZ,
    recorded_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_visitor_logs_hostel ON public.visitor_logs(hostel_id);
CREATE INDEX IF NOT EXISTS idx_visitor_logs_student ON public.visitor_logs(student_id);
