-- =============================================================================
-- Migration 011: Mess Management & Meal Skips
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.meal_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name IN ('BR', 'LN', 'SN', 'DN')),
    description TEXT,
    time_from TIME,
    time_to TIME,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    vegetarian BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    day_of_week CHAR(1) NOT NULL CHECK (day_of_week BETWEEN '0' AND '6'),
    meal_type_id BIGINT NOT NULL REFERENCES public.meal_types(id) ON DELETE RESTRICT,
    is_recurring BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_menu_hostel_day_meal UNIQUE (hostel_id, day_of_week, meal_type_id)
);

CREATE TABLE IF NOT EXISTS public.menu_item_links (
    menu_id BIGINT NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
    PRIMARY KEY (menu_id, item_id)
);

-- Hardened Meal Skip with meal_type_id NOT NULL
CREATE TABLE IF NOT EXISTS public.student_meal_skips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
    hostel_id BIGINT NOT NULL REFERENCES public.hostels(id) ON DELETE RESTRICT,
    date DATE NOT NULL,
    meal_type_id BIGINT NOT NULL REFERENCES public.meal_types(id) ON DELETE RESTRICT,
    skip_type TEXT NOT NULL DEFAULT 'SKIP' CHECK (skip_type IN ('SKIP', 'LEAVE', 'RETURN')),
    reason TEXT,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_student_meal_skip UNIQUE (student_id, date, meal_type_id)
);

CREATE INDEX IF NOT EXISTS idx_meal_skips_hostel_date ON public.student_meal_skips(hostel_id, date);
