-- =============================================================================
-- Migration 018: Caretakers Table and Schema
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.hostel_caretakers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT NOT NULL,
    experience INTEGER NOT NULL DEFAULT 0,
    address TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.hostel_caretakers ENABLE ROW LEVEL SECURITY;

-- Read policy: Authenticated users can view caretakers
CREATE POLICY "Authenticated users can view caretakers"
    ON public.hostel_caretakers FOR SELECT
    TO authenticated
    USING (true);

-- Admin policy: Admins can insert/update/delete caretakers
CREATE POLICY "Admins can manage caretakers"
    ON public.hostel_caretakers FOR ALL
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Seed initial realistic caretakers directly in the DB table
INSERT INTO public.hostel_caretakers (name, email, phone, experience)
VALUES 
  ('Suresh Sharma', 'suresh.caretaker@amc.edu', '9822334455', 4),
  ('Ramesh Patel', 'ramesh.caretaker@amc.edu', '9833445566', 6)
ON CONFLICT DO NOTHING;
