-- =============================================================================
-- Migration 022: Warden and Security Tables for Staff Directory
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.hostel_wardens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT NOT NULL,
    designation TEXT NOT NULL DEFAULT 'Hostel Warden',
    experience INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.hostel_wardens ENABLE ROW LEVEL SECURITY;

-- Read policy: Authenticated users can view wardens
CREATE POLICY "Authenticated users can view wardens"
    ON public.hostel_wardens FOR SELECT
    TO authenticated
    USING (true);

-- Admin policy: Admins can manage wardens
CREATE POLICY "Admins can manage wardens"
    ON public.hostel_wardens FOR ALL
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());


CREATE TABLE IF NOT EXISTS public.security_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT NOT NULL,
    designation TEXT NOT NULL DEFAULT 'Security Guard',
    experience INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.security_staff ENABLE ROW LEVEL SECURITY;

-- Read policy: Authenticated users can view security staff
CREATE POLICY "Authenticated users can view security staff"
    ON public.security_staff FOR SELECT
    TO authenticated
    USING (true);

-- Admin policy: Admins can manage security staff
CREATE POLICY "Admins can manage security staff"
    ON public.security_staff FOR ALL
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());
